add guard for bad alignment option #1072
latex3/latex2e pull request #1154
Opened 2023-10-26 21:07 UTC by davidcarlisle

# Internal housekeeping

## Status of pull request

- Ready to merge (apart from ltnews update which will be added shortly)

## Checklist of required changes before merge will be approved
- [X] Test file(s) added
- [X] Version and date string updated in changed source files
- [X] Relevant `\changes` entries in source included
- [X] Relevant `changes.txt` updated (actually relative to PR1153 to save merge conflict later)
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated  (not yet)

In addition to the `\makebox` case in #1072  the same construct is used in `\framebox` and `\parbox` so this updates all three.

2023-10-26 21:45 UTC, josephwright requested changes

2023-10-26 21:45 UTC, josephwright commented on base/doc/ltnews38.tex
> +This will now produce a warning and act like the default `c` alignment.
`\texttt{c}`

2023-10-26 21:59 UTC, davidcarlisle commented on base/doc/ltnews38.tex
> +This will now produce a warning and act like the default `c` alignment.
too much markdown, not enough TeX :(

2023-10-29 11:56 UTC, FrankMittelbach commented
Assuming this passes all tests I think it is ready to go

2023-10-29 17:09 UTC, merged