Fix inconsistent behavior of expansion of key-value package options
latex3/latex2e pull request #1300
Opened 2024-03-19 00:12 UTC by muzimuzhi

When a package is loaded the first time, its option list is first expanded by one step then stored as raw option list. This PR makes the expansion behavior consistent for second loading.

The change is similar to those in https://github.com/latex3/latex2e/commit/5a5f6a68922183271d460cb9006fa2b1ea27a718, which fixed #580.

https://github.com/latex3/latex2e/blob/9c5023c97d3658530f7bb0635c5fcd84b87d89c3/base/ltclass.dtx#L1327-L1334

Is rollback needed?

# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Ready to merge

## Checklist of required changes before merge will be approved
- [x] Test file(s) added
- [x] Version and date string updated in changed source files
- [x] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [ ] Rollback provided (if necessary)?
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

2024-03-19 00:26 UTC, muzimuzhi commented
Bad, using `` `\@pass@ptions` `` in commit message tagged a random user and there seems to be no simple solution.

https://stackoverflow.com/questions/38862079/github-commit-message-escape-character

2024-03-21 11:21 UTC, josephwright requested changes
I think we need a short news entry here, please. Otherwise looks good.

2024-03-21 19:51 UTC, davidcarlisle approved these changes

2024-03-21 20:09 UTC, FrankMittelbach approved these changes

2024-03-22 08:08 UTC, muzimuzhi commented
Added news entry, hard-wrapped long code lines, and updated date.

2024-03-22 08:08 UTC, josephwright approved these changes

2024-03-22 08:08 UTC, merged