ltcmd: implement SplitKeyval argument processor
latex3/latex2e pull request #1350
Opened 2024-05-19 15:51 UTC by Skillmon

**READ ME FIRST**: Please understand that in most cases we will not be able to merge a pull request because there are a lot of internal activities needed when updating the LaTeX2e sources. If you have a code suggestion please discuss it with the team first.

*Pull requests in this repository are intended for LaTeX Team members only.*

# Internal housekeeping

## Status of pull request

- Feedback wanted 
- Under development
- Ready to merge

## Checklist of required changes before merge will be approved
- [x] Test file(s) added
- [x] Version and date string updated in changed source files
- [ ] Relevant `\changes` entries in source included
- [ ] Relevant `changes.txt` updated
- [ ] Rollback provided (if necessary)?
- [ ] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

2024-05-27 14:18 UTC, josephwright commented
We'll look at this after the June 2024 release ...

2024-06-03 07:01 UTC, josephwright commented
Could you rebase onto develop?

2025-04-22 06:35 UTC, josephwright commented
Was just looking back at this -could you rebase and update dates/`changes.txt` and I'll look at it properly.

2025-04-22 16:37 UTC, josephwright approved these changes
Looks good to me, though we will want a `changes.txt` entry and probably something for `ltnews` (they can be added later).

2025-04-22 16:37 UTC, Skillmon commented
Done.

Another question: `expkv-cs` has the `...` notation to collect any undefined keys encountered in an argument instead of throwing an error. Is that something I should add here as well (would be similar to `\keys_set_known:nnN` but forward the undefined keys as another element in the split arguments)?

2025-04-26 11:41 UTC, davidcarlisle requested changes
The code seems Ok I just made some comments on the text in the news.

But more generally it would be good to document the motivation for this. The documentation comments in a few places it should only be used for small lists of keys, but doesn't really say what advantage it has for small lists over the presumed alternative that would work for larger key sets of passing `#1` to a standard keyval processor so saving the three keys as \tmpa \tmpb and \tmpc then calling \ExpArgs{ooo}\FunctionOfThree{\tnpa}[\tmbb}{\tmpc}`

Is this quicker?

2025-04-26 11:41 UTC, davidcarlisle commented on base/doc/ltnews41.tex
> +For very simple key=value setups with only a handful simple keys a new argument
```suggestion
For very simple key=value setups with only a handful simple keys, a new argument
```

2025-04-26 11:41 UTC, davidcarlisle commented on base/doc/ltnews41.tex
> +processor \cs{SplitKeyval} is added that works similar to \cs{SplitArgument} but
```suggestion
processor \cs{SplitKeyval} is added that works in a similar way to \cs{SplitArgument} but
```

2025-04-26 11:41 UTC, davidcarlisle commented on base/doc/ltnews41.tex
> +value an empty value will be forwarded. We can then use the macro and get the
```suggestion
value an empty value, will be forwarded. We can then use the macro and get the
```

2025-04-26 18:42 UTC, Skillmon commented
> Is this quicker?

No, it isn't. In fact it's slower by roughly a factor 2 because it does the key-setup and then parsing on each usage instead of a one-off setup.

But it's much simpler, so is easier for document authors (I'd say this isn't really meant for package authors), compare the following:

```latex
\NewDocumentCommand\processor{>{\SplitKeyval{keyA=A,keyB,keyC=C}}m}
  { \use_none:nnn #1 }
```

vs

```latex
\keys_define:nn { test }
  {
     keyA .tl_set:N = \l_test_keyA_tl
    ,keyA .initial:n = A
    ,keyB .tl_set:N = \l_test_keyB_tl
    ,keyB .initial:V = \c_novalue_tl
    ,keyC .tl_set:N = \l_test_keyC_tl
    ,keyC .initial:n = C
  }
\NewDocumentCommand\keysusing{m}
  {
    \group_begin:
      \keys_set:nn {test} {#1}
      \exp_args:NNVVV
    \group_end:
    \use_none:nnn \l_test_keyA_tl \l_test_keyB_tl \l_test_keyC_tl
  }
\exp_args_generate:n {NVVV}
```

(even if the group handling shouldn't apply, the code becomes only marginally simpler, and for users it could involve expansion handling, depending on their use case.)

So the *only* selling point is indeed simplicity.

2025-04-26 18:44 UTC, Skillmon commented on base/doc/ltnews41.tex
> +value an empty value will be forwarded. We can then use the macro and get the
I think the comma should be after the first "value" here, not after the second?

2025-04-26 18:50 UTC, davidcarlisle approved these changes
I guess simplicity argument is OK since it isn't adding a lot of code

2025-04-26 18:51 UTC, davidcarlisle commented on base/doc/ltnews41.tex
> +value an empty value will be forwarded. We can then use the macro and get the
yes, sorry

2025-04-27 10:42 UTC, FrankMittelbach commented
I am a bit concerned that code like this ends up in packages and then people complain about L3/ LaTeX being slow. So I guess it's a big disclaimer that this is only for user level and not for package code, including advise what to do on the package level instead.

2025-04-27 11:18 UTC, davidcarlisle commented
@FrankMittelbach  @Skillmon  that's my concern as well. I don't think "typical document use" is as complicated as the above comment suggests, in particular you don't need to drop into L3 syntax

```
\documentclass{article}

\NewDocumentCommand\threeargs{mmm}{-#1-#2-#3-}
\DeclareKeys[me]{
  key1 .store = \tmpa,
  key2 .store = \tmpb,
  key3 .store = \tmpc
}
\NewDocumentCommand\keyargs{O{}}{%
  \renewcommand\tmpa{defa}%
  \renewcommand\tmpb{defb}%
  \renewcommand\tmpc{defc}%
  \SetKeys[me]{#1}%
  \ExpandArgs{ooo}\threeargs\tmpa\tmpb\tmpc
  }
\begin{document}

\keyargs

\keyargs[key2=TWO]

\end{document}
```

This isn't really significantly more complicated than the version here.
It doesn't group the temp commands but the calling command can group if that us needed.

2025-04-28 21:15 UTC, Skillmon commented
Feel free to drop it :) I could write a fast version by doing some caching, setting it up during command-definition etc., but that would turn out to get rather complicated for something that's generally just a small and less powerful variant of something already there.

So I don't have any bad feelings here. TBH, I already forgot about it; it just came up last week in the TeX.SX chat because some user asked me whether this was available nowadays.

2025-04-30 11:02 UTC, josephwright commented
OK, based on the review comments I'll close.

2025-04-30 11:02 UTC, closed without merging