Gh1585 allowing \fpeval in array preamble
latex3/latex2e pull request #1586
Opened 2024-12-17 23:53 UTC by FrankMittelbach

# Internal housekeeping

## Status of pull request

 Ready to merge

## Checklist of required changes before merge will be approved
- [x] Test file(s) added
- [x] Version and date string updated in changed source files
- [x] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [n/a] Rollback provided (if necessary)?
- [x] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

There is one surprising test suite diff for tagging-002-longtable. That needs checking and verification.

2024-12-18 12:01 UTC, FrankMittelbach commented
I've done some minimal adjustment to longtable, to make it work with the change in array. It could probably be simplified by using \@startpbox@preamble and then keeping \@startpbox for the action rather than having \@startpbox and \@startpboxaction with the same top-level definitions. But  that might mean more checking on other packages how they use \@startpbox and \@mkpream. So I'm not sure it is worth the effort. @davidcarlisle does it looks okay to you?

2024-12-19 16:41 UTC, Skillmon commented on required/tools/array.dtx
> +%    preamble built-up \cs{@startpbox@action} that does the actual work.
```suggestion
%    preamble built-up \cs{@startpbox@action} does the actual work.
```

2024-12-19 16:41 UTC, Skillmon commented on required/tools/array.dtx
> +%      \cs{@startpbox@action} later to do the real work (gh/1585)}
Something strange happened here (and in the line above), looks like you rewrote that sentence and forgot to delete the old version.

2024-12-28 08:31 UTC, josephwright requested changes
We seem to have two different things going on here: the `changes.txt` edit it nothing to do with the rest of the PR!

2024-12-28 08:43 UTC, FrankMittelbach commented
> We seem to have two different things going on here: the `changes.txt` edit it nothing to do with the rest of the PR!

when I fixed 1418 I had by mistake this PR checked out, which is why it now contains both the changes for that (documented in base) as well as the change for this PR (documented in changes of tools). I was too lazy to back it out, so this PR contains now the fixes for both issues, hence the unrelated changes text and the fixes to doc.dtx

2024-12-28 09:38 UTC, josephwright approved these changes

2024-12-28 11:34 UTC, davidcarlisle approved these changes

2024-12-28 13:29 UTC, merged

2025-01-03 02:28 UTC, car222222 reviewed
I have now, too late?, found some (probably)necessary corrections here.

I cannot now Approve it, not sure why?

2025-01-03 21:41 UTC, FrankMittelbach commented on base/doc/ltnews41.tex
> +the arguments to \texttt{p}, \texttt{m}, or \texttt{b} columns were
not sure, they have been expanded but aren't any longer, so "get" seems wrong "got expanded" perhaps?

2025-01-03 21:52 UTC, FrankMittelbach commented
> I have now, too late?, found some (probably) necessary corrections here.

added (with one query)

> I cannot now Approve it, not sure why?

same reason as before ... after a while it got merged (two approvals), then you can only comment but not review any longer.

2025-01-04 01:36 UTC, car222222 commented
Understood, but the app is a bit confused about this: it still has the normal "Review" button and functionality, up to the final stage where there are no options for Approval, etc. (And it does not appear as a "Review", although within the change files it looks like one.)

2025-01-04 01:40 UTC, car222222 commented on base/doc/ltnews41.tex
> +the arguments to \texttt{p}, \texttt{m}, or \texttt{b} columns were
Yes, my typo! I meant "got".

2025-01-04 09:11 UTC, FrankMittelbach commented
yes I agree it is a bit odd; your only indication is that it says merged on top (and then in the end when you can't actually finish the review) - happened to me a few times as well. But at least the comments get added and distributed so all that is lost is really to be able to say "approved" or "changes requested" which kind of makes sense because the merge has already happened.

2025-01-04 09:14 UTC, FrankMittelbach commented on base/doc/ltnews41.tex
> +the arguments to \texttt{p}, \texttt{m}, or \texttt{b} columns were
ok updated

2025-01-06 07:08 UTC, car222222 commented
Agreed that it makes sense!  But it would be better if it were explained in detail somewhere (maybe it is!??).  

Actually this seems to be a general problem with apps and the like these days: it is seldom clear how or where to find simple explanations of how they can, or should, be used.  

And, especially in iOS apps, “buttonless”(or minimal buttons) seems to be the new normal and preferred interface.