Gh1150 docstrip
latex3/latex2e pull request #1595
Opened 2024-12-23 15:39 UTC by FrankMittelbach

# Internal housekeeping

## Status of pull request

- Ready to merge

## Checklist of required changes before merge will be approved
- [n/a] Test file(s) added
- [x] Version and date string updated in changed source files
- [x] Relevant `\changes` entries in source included
- [x] Relevant `changes.txt` updated
- [n/a] Rollback provided (if necessary)?
- [x] `ltnewsX.tex` (and/or `latexchanges.tex`) updated

2024-12-23 16:07 UTC, muzimuzhi requested changes
Typos and minor improvements.

2024-12-23 16:07 UTC, muzimuzhi commented on base/doc/ltnews41.tex
> +the macro used to stored it was reused for denoting the output
```suggestion
the macro used to store it was reused for denoting the output
```

2024-12-23 16:07 UTC, muzimuzhi commented on base/docstrip.dtx
> +%    as a preamble or postamble or for some other purpose, chances are
```suggestion
%    as a preamble or postamble or for some other purposes, chances are
```

2024-12-23 16:07 UTC, muzimuzhi commented on base/docstrip.dtx
> +       \errmessage{Declared postamble name \string#1 not allowed if
Reduce indent level by 1.
```suggestion
     \errmessage{Declared postamble name \string#1 not allowed if
```

2024-12-28 08:45 UTC, josephwright approved these changes

2024-12-29 01:53 UTC, muzimuzhi approved these changes
one spelling

2024-12-29 01:53 UTC, muzimuzhi commented on base/docstrip.dtx
> +%    If it matches the name of the current preamble or postable then
```suggestion
%    If it matches the name of the current preamble or postamble then
```

2024-12-29 12:09 UTC, FrankMittelbach commented on base/docstrip.dtx
> +%    If it matches the name of the current preamble or postable then
thanks, as usual

2024-12-29 12:38 UTC, merged