Lt4.15
latex3/latex2e pull request #545
Opened 2021-04-18 08:37 UTC by davidcarlisle

## Status of pull request

- Feedback wanted 
- Under development
- Ready to merge

## Checklist of required changes before merge will be approved
- [ .] Test file(s) added
- [ .] Version and date string updated in changed source files
- [. ] Relevant `\changes` entries in source included
- [ .] Relevant `changes.txt` updated
- [ ] `ltnewsX.tex` updated (covered by existing entry)

2021-04-18 08:49 UTC, FrankMittelbach requested changes

2021-04-18 08:49 UTC, FrankMittelbach commented on required/tools/longtable.dtx
> +%      {silence \cs{vbadness}}
gonna be a long month this one :-)

2021-04-18 08:50 UTC, FrankMittelbach commented
you may have to merge in development to get rid of test file problems due to the linebreaking issues in the suite at the moment.

2021-04-18 09:13 UTC, davidcarlisle commented
Yes I believe the current plan was to wait until you/Phelype had finished
the current round of hook adjustments before merging in these smaller
feature branches, the merge this way just adding the LT update to develop
looks like it should merge cleanly,

On Sun, 18 Apr 2021 at 09:50, Frank Mittelbach ***@***.***>
wrote:

> you may have to merge in development to get rid of test file problems due
> to the linebreaking issues in the suite at the moment.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/latex3/latex2e/pull/545#issuecomment-821957050>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJVYAWPPC4BWLOEMALCN2TTJKMOLANCNFSM43D7LNZA>
> .
>

2021-04-18 09:18 UTC, FrankMittelbach commented
> Yes I believe the current plan was to wait until you/Phelype had finished

didn't put enough commas I guess:-) I meant merge current develp into your branch because I have updated all the tests that fail in develop, that should give you a chance to see that your changes do not generate new diffs

2021-04-22 14:43 UTC, FrankMittelbach approved these changes
in my opinion this is ready for merge

2021-04-23 14:16 UTC, merged